---
- name: Get system subscription status
  command: subscription-manager status
  register: oasis_roles_rhsm_subscription
  changed_when: false
  failed_when: false

- name: Get system subscribed pools
  # This always exits 0 whether the system is subscribed or not;
  # stdout is empty on an unsubbed system.
  command: subscription-manager list --consumed --pool-only
  register: oasis_roles_rhsm_pools
  changed_when: false
  failed_when: false

- name: Register Role Output
  set_fact:
    oasis_roles_rhsm:
      subscribed: "{{ oasis_roles_rhsm_subscription.rc == 0 }}"
      subscribed_pool_ids: "{{ oasis_roles_rhsm_pools.stdout.split() }}"

      # Included here mainly for use by tests to ensure the version-based
      # task module selections actually work in different versions of ansible.
      _rhsm_repository_task: "{{ _rhsm_repository_task }}"
      _rhsm_release_task: "{{ _rhsm_release_task }}"
