---
- name: Disable repositories
  action: "{{ _rhsm_repository_task }}"
  args:
    state: disabled
    name: "{{ rhsm_repositories.disabled | default([]) }}"
  when: "'disabled' in rhsm_repositories"

- name: Enable repositories
  action: "{{ _rhsm_repository_task }}"
  args:
    state: enabled
    name: "{{ rhsm_repositories.enabled | default([]) }}"
  when: "'enabled' in rhsm_repositories"
